# Generated by Django 3.2.8 on 2021-10-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CheckIn', '0002_alter_personalcheck_workinghours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalcheck',
            name='workingHours',
            field=models.CharField(max_length=200),
        ),
    ]
