# Generated by Django 3.2.8 on 2021-10-07 11:39

import computed_property.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CheckIn', '0003_alter_personalcheck_workinghours'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalcheck',
            name='w_hours',
            field=computed_property.fields.ComputedTextField(compute_from='calculation', default='test', editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personalcheck',
            name='workingHours',
            field=models.CharField(max_length=300),
        ),
    ]
