# Generated by Django 3.2.8 on 2021-10-07 11:43

import computed_property.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CheckIn', '0004_auto_20211007_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalcheck',
            name='workingHours',
        ),
        migrations.AlterField(
            model_name='personalcheck',
            name='w_hours',
            field=computed_property.fields.ComputedTextField(compute_from='hours', editable=False),
        ),
    ]
