# Generated by Django 3.2.8 on 2021-10-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CheckIn', '0006_alter_personalcheck_w_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalcheck',
            name='period',
            field=models.CharField(default='test', max_length=300),
            preserve_default=False,
        ),
    ]
