# Generated by Django 3.2.8 on 2021-10-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CheckIn', '0008_personalcheck_isworking'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalcheck',
            name='day',
            field=models.DateField(default='2021-01-01'),
            preserve_default=False,
        ),
    ]
