# Generated by Django 3.2.8 on 2021-10-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CheckIn', '0009_personalcheck_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalcheck',
            name='finish_time',
            field=models.TimeField(null=True),
        ),
    ]
