# Generated by Django 3.2.8 on 2021-10-11 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CheckIn', '0010_alter_personalcheck_finish_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalcheck',
            old_name='personal',
            new_name='personal_id',
        ),
    ]
