# Generated by Django 3.2.8 on 2021-10-11 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CheckIn', '0011_rename_personal_personalcheck_personal_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalcheck',
            old_name='personal_id',
            new_name='personal',
        ),
    ]
