# Generated by Django 3.2.8 on 2021-10-11 02:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CheckIn', '0012_rename_personal_id_personalcheck_personal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalcheck',
            name='personal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal', to=settings.AUTH_USER_MODEL),
        ),
    ]
